goal(posizione_tessera(1,0)).
goal(posizione_tessera(2,1)).
goal(posizione_tessera(3,2)).
goal(posizione_tessera(4,3)).
goal(posizione_tessera(5,4)).
goal(posizione_tessera(6,5)).
goal(posizione_tessera(7,6)).
goal(posizione_tessera(8,7)).
goal(posizione_tessera(0,8)).
