goal(posizione_tessera(1,0)).
goal(posizione_tessera(2,1)).
goal(posizione_tessera(3,2)).
goal(posizione_tessera(4,3)).
goal(posizione_tessera(5,4)).
goal(posizione_tessera(6,5)).
goal(posizione_tessera(7,6)).
goal(posizione_tessera(8,7)).
goal(posizione_tessera(9,8)).
goal(posizione_tessera(10,9)).
goal(posizione_tessera(11,10)).
goal(posizione_tessera(12,11)).
goal(posizione_tessera(13,12)).
goal(posizione_tessera(14,13)).
goal(posizione_tessera(15,14)).
goal(posizione_tessera(0,15)).
